[phases.setup]
nixPkgs = ['php82', 'php82Extensions.mysqli', 'php82Extensions.pdo', 'php82Extensions.pdo_mysql', 'nodejs_20']

[phases.install]
cmds = ['cd CopaLink/websocket && npm install']

[start]
cmd = 'php -S 0.0.0.0:$PORT -t CopaLink'
